/*
VRChat API Documentation

Testing FilesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"testing"

	openapiclient "github.com/StarLight-Oliver/vrchatapi-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_vrchatapi_FilesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FilesAPIService CreateFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.CreateFile(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService CreateFileVersion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FilesAPI.CreateFileVersion(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService DeleteFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FilesAPI.DeleteFile(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService DeleteFileVersion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32

		resp, httpRes, err := apiClient.FilesAPI.DeleteFileVersion(context.Background(), fileId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService DownloadFileVersion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32

		resp, httpRes, err := apiClient.FilesAPI.DownloadFileVersion(context.Background(), fileId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService FinishFileDataUpload", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32
		var fileType string

		resp, httpRes, err := apiClient.FilesAPI.FinishFileDataUpload(context.Background(), fileId, versionId, fileType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetAdminAssetBundle", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var adminAssetBundleId string

		resp, httpRes, err := apiClient.FilesAPI.GetAdminAssetBundle(context.Background(), adminAssetBundleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetContentAgreementStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.GetContentAgreementStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FilesAPI.GetFile(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetFileAnalysis", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32

		resp, httpRes, err := apiClient.FilesAPI.GetFileAnalysis(context.Background(), fileId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetFileAnalysisSecurity", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32

		resp, httpRes, err := apiClient.FilesAPI.GetFileAnalysisSecurity(context.Background(), fileId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetFileAnalysisStandard", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32

		resp, httpRes, err := apiClient.FilesAPI.GetFileAnalysisStandard(context.Background(), fileId, versionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetFileDataUploadStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32
		var fileType string

		resp, httpRes, err := apiClient.FilesAPI.GetFileDataUploadStatus(context.Background(), fileId, versionId, fileType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService GetFiles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.GetFiles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService SetGroupGalleryFileOrder", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.SetGroupGalleryFileOrder(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService StartFileDataUpload", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string
		var versionId int32
		var fileType string

		resp, httpRes, err := apiClient.FilesAPI.StartFileDataUpload(context.Background(), fileId, versionId, fileType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService SubmitContentAgreement", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.SubmitContentAgreement(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService UpdateAssetReviewNotes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var assetReviewId string

		httpRes, err := apiClient.FilesAPI.UpdateAssetReviewNotes(context.Background(), assetReviewId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService UploadGalleryImage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.UploadGalleryImage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService UploadIcon", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.UploadIcon(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService UploadImage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.FilesAPI.UploadImage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
