/*
VRChat API Documentation

Testing InviteAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_InviteAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InviteAPIService GetInviteMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string
		var messageType openapiclient.InviteMessageType
		var slot int32

		resp, httpRes, err := apiClient.InviteAPI.GetInviteMessage(context.Background(), userId, messageType, slot).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService GetInviteMessages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string
		var messageType openapiclient.InviteMessageType

		resp, httpRes, err := apiClient.InviteAPI.GetInviteMessages(context.Background(), userId, messageType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService InviteMyselfTo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var worldId string
		var instanceId string

		resp, httpRes, err := apiClient.InviteAPI.InviteMyselfTo(context.Background(), worldId, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService InviteUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string

		resp, httpRes, err := apiClient.InviteAPI.InviteUser(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService InviteUserWithPhoto", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string

		resp, httpRes, err := apiClient.InviteAPI.InviteUserWithPhoto(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService RequestInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string

		resp, httpRes, err := apiClient.InviteAPI.RequestInvite(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService RequestInviteWithPhoto", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string

		resp, httpRes, err := apiClient.InviteAPI.RequestInviteWithPhoto(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService ResetInviteMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string
		var messageType openapiclient.InviteMessageType
		var slot int32

		resp, httpRes, err := apiClient.InviteAPI.ResetInviteMessage(context.Background(), userId, messageType, slot).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService RespondInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var notificationId string

		resp, httpRes, err := apiClient.InviteAPI.RespondInvite(context.Background(), notificationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService RespondInviteWithPhoto", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var notificationId string

		resp, httpRes, err := apiClient.InviteAPI.RespondInviteWithPhoto(context.Background(), notificationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InviteAPIService UpdateInviteMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string
		var messageType openapiclient.InviteMessageType
		var slot int32

		resp, httpRes, err := apiClient.InviteAPI.UpdateInviteMessage(context.Background(), userId, messageType, slot).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
