/*
VRChat API Documentation

Testing AvatarsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"testing"

	openapiclient "github.com/StarLight-Oliver/vrchatapi-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_vrchatapi_AvatarsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AvatarsAPIService CreateAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AvatarsAPI.CreateAvatar(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService DeleteAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		resp, httpRes, err := apiClient.AvatarsAPI.DeleteAvatar(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService DeleteImpostor", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		httpRes, err := apiClient.AvatarsAPI.DeleteImpostor(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService EnqueueImpostor", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		resp, httpRes, err := apiClient.AvatarsAPI.EnqueueImpostor(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService GetAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		resp, httpRes, err := apiClient.AvatarsAPI.GetAvatar(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService GetAvatarStyles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AvatarsAPI.GetAvatarStyles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService GetFavoritedAvatars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AvatarsAPI.GetFavoritedAvatars(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService GetImpostorQueueStats", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AvatarsAPI.GetImpostorQueueStats(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService GetLicensedAvatars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AvatarsAPI.GetLicensedAvatars(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService GetOwnAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var userId string

		resp, httpRes, err := apiClient.AvatarsAPI.GetOwnAvatar(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService SearchAvatars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AvatarsAPI.SearchAvatars(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService SelectAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		resp, httpRes, err := apiClient.AvatarsAPI.SelectAvatar(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService SelectFallbackAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		resp, httpRes, err := apiClient.AvatarsAPI.SelectFallbackAvatar(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AvatarsAPIService UpdateAvatar", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var avatarId string

		resp, httpRes, err := apiClient.AvatarsAPI.UpdateAvatar(context.Background(), avatarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
