/*
VRChat API Documentation

Testing PropsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_PropsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PropsAPIService CreateProp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropsAPI.CreateProp(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService DeleteProp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propId string

		httpRes, err := apiClient.PropsAPI.DeleteProp(context.Background(), propId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService GetProp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propId string

		resp, httpRes, err := apiClient.PropsAPI.GetProp(context.Background(), propId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService GetPropPublishStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propId string

		resp, httpRes, err := apiClient.PropsAPI.GetPropPublishStatus(context.Background(), propId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService ListProps", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropsAPI.ListProps(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService PublishProp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propId string

		resp, httpRes, err := apiClient.PropsAPI.PublishProp(context.Background(), propId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService UnpublishProp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propId string

		resp, httpRes, err := apiClient.PropsAPI.UnpublishProp(context.Background(), propId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropsAPIService UpdateProp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propId string

		resp, httpRes, err := apiClient.PropsAPI.UpdateProp(context.Background(), propId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
