/*
VRChat API Documentation

Testing FavoritesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_FavoritesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FavoritesAPIService AddFavorite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FavoritesAPI.AddFavorite(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService ClearFavoriteGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var favoriteGroupType string
		var favoriteGroupName string
		var userId string

		resp, httpRes, err := apiClient.FavoritesAPI.ClearFavoriteGroup(context.Background(), favoriteGroupType, favoriteGroupName, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService GetFavoriteGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var favoriteGroupType string
		var favoriteGroupName string
		var userId string

		resp, httpRes, err := apiClient.FavoritesAPI.GetFavoriteGroup(context.Background(), favoriteGroupType, favoriteGroupName, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService GetFavoriteGroups", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FavoritesAPI.GetFavoriteGroups(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService GetFavoriteLimits", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FavoritesAPI.GetFavoriteLimits(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService GetFavorites", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FavoritesAPI.GetFavorites(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService RemoveFavorite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var favoriteId string

		resp, httpRes, err := apiClient.FavoritesAPI.RemoveFavorite(context.Background(), favoriteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FavoritesAPIService UpdateFavoriteGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var favoriteGroupType string
		var favoriteGroupName string
		var userId string

		httpRes, err := apiClient.FavoritesAPI.UpdateFavoriteGroup(context.Background(), favoriteGroupType, favoriteGroupName, userId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
