/*
VRChat API Documentation

Testing CalendarAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_CalendarAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CalendarAPIService CreateGroupCalendarEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.CalendarAPI.CreateGroupCalendarEvent(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService DeleteGroupCalendarEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string
		var calendarId string

		resp, httpRes, err := apiClient.CalendarAPI.DeleteGroupCalendarEvent(context.Background(), groupId, calendarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService DiscoverCalendarEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CalendarAPI.DiscoverCalendarEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService FollowGroupCalendarEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string
		var calendarId string

		resp, httpRes, err := apiClient.CalendarAPI.FollowGroupCalendarEvent(context.Background(), groupId, calendarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetCalendarEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CalendarAPI.GetCalendarEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetFeaturedCalendarEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CalendarAPI.GetFeaturedCalendarEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetFollowedCalendarEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CalendarAPI.GetFollowedCalendarEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetGroupCalendarEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string
		var calendarId string

		resp, httpRes, err := apiClient.CalendarAPI.GetGroupCalendarEvent(context.Background(), groupId, calendarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetGroupCalendarEventICS", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string
		var calendarId string

		resp, httpRes, err := apiClient.CalendarAPI.GetGroupCalendarEventICS(context.Background(), groupId, calendarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetGroupCalendarEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.CalendarAPI.GetGroupCalendarEvents(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService GetGroupNextCalendarEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.CalendarAPI.GetGroupNextCalendarEvent(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService SearchCalendarEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CalendarAPI.SearchCalendarEvents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CalendarAPIService UpdateGroupCalendarEvent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string
		var calendarId string

		resp, httpRes, err := apiClient.CalendarAPI.UpdateGroupCalendarEvent(context.Background(), groupId, calendarId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
