/*
VRChat API Documentation

Testing InstancesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_InstancesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstancesAPIService CloseInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var worldId string
		var instanceId string

		resp, httpRes, err := apiClient.InstancesAPI.CloseInstance(context.Background(), worldId, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstancesAPIService CreateInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstancesAPI.CreateInstance(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstancesAPIService GetInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var worldId string
		var instanceId string

		resp, httpRes, err := apiClient.InstancesAPI.GetInstance(context.Background(), worldId, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstancesAPIService GetInstanceByShortName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shortName string

		resp, httpRes, err := apiClient.InstancesAPI.GetInstanceByShortName(context.Background(), shortName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstancesAPIService GetRecentLocations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstancesAPI.GetRecentLocations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstancesAPIService GetShortName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var worldId string
		var instanceId string

		resp, httpRes, err := apiClient.InstancesAPI.GetShortName(context.Background(), worldId, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
