/*
VRChat API Documentation

Testing InventoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_InventoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InventoryAPIService ConsumeOwnInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.ConsumeOwnInventoryItem(context.Background(), inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService DeleteOwnInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.DeleteOwnInventoryItem(context.Background(), inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService EquipOwnInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.EquipOwnInventoryItem(context.Background(), inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetInventory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InventoryAPI.GetInventory(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetInventoryCollections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InventoryAPI.GetInventoryCollections(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetInventoryDrops", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InventoryAPI.GetInventoryDrops(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetInventoryTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryTemplateId string

		resp, httpRes, err := apiClient.InventoryAPI.GetInventoryTemplate(context.Background(), inventoryTemplateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetOwnInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.GetOwnInventoryItem(context.Background(), inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService GetUserInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string
		var inventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.GetUserInventoryItem(context.Background(), userId, inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService ShareInventoryItemDirect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InventoryAPI.ShareInventoryItemDirect(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService ShareInventoryItemPedestal", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InventoryAPI.ShareInventoryItemPedestal(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService SpawnInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InventoryAPI.SpawnInventoryItem(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService UnequipOwnInventorySlot", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryItemId openapiclient.InventoryEquipSlot

		resp, httpRes, err := apiClient.InventoryAPI.UnequipOwnInventorySlot(context.Background(), inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InventoryAPIService UpdateOwnInventoryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inventoryItemId string

		resp, httpRes, err := apiClient.InventoryAPI.UpdateOwnInventoryItem(context.Background(), inventoryItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
