/*
VRChat API Documentation

Testing PrintsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_PrintsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PrintsAPIService DeletePrint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printId string

		httpRes, err := apiClient.PrintsAPI.DeletePrint(context.Background(), printId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrintsAPIService EditPrint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printId string

		resp, httpRes, err := apiClient.PrintsAPI.EditPrint(context.Background(), printId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrintsAPIService GetPrint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printId string

		resp, httpRes, err := apiClient.PrintsAPI.GetPrint(context.Background(), printId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrintsAPIService GetUserPrints", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userId string

		resp, httpRes, err := apiClient.PrintsAPI.GetUserPrints(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrintsAPIService UploadPrint", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PrintsAPI.UploadPrint(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
