/*
VRChat API Documentation

Testing JamsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vrchatapi/vrchatapi-go"
)

func Test_vrchatapi_JamsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test JamsAPIService GetJam", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jamId string

		resp, httpRes, err := apiClient.JamsAPI.GetJam(context.Background(), jamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JamsAPIService GetJamSubmissions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jamId string

		resp, httpRes, err := apiClient.JamsAPI.GetJamSubmissions(context.Background(), jamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test JamsAPIService GetJams", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.JamsAPI.GetJams(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
