/*
VRChat API Documentation

Testing WorldsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vrchatapi

import (
	"context"
	"testing"

	openapiclient "github.com/StarLight-Oliver/vrchatapi-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_vrchatapi_WorldsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorldsAPIService CreateWorld", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WorldsAPI.CreateWorld(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService DeleteWorld", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		httpRes, err := apiClient.WorldsAPI.DeleteWorld(context.Background(), worldId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetActiveWorlds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WorldsAPI.GetActiveWorlds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetFavoritedWorlds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WorldsAPI.GetFavoritedWorlds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetRecentWorlds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WorldsAPI.GetRecentWorlds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetWorld", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		resp, httpRes, err := apiClient.WorldsAPI.GetWorld(context.Background(), worldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetWorldInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string
		var instanceId string

		resp, httpRes, err := apiClient.WorldsAPI.GetWorldInstance(context.Background(), worldId, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetWorldMetadata", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		resp, httpRes, err := apiClient.WorldsAPI.GetWorldMetadata(context.Background(), worldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService GetWorldPublishStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		resp, httpRes, err := apiClient.WorldsAPI.GetWorldPublishStatus(context.Background(), worldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService PublishWorld", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		httpRes, err := apiClient.WorldsAPI.PublishWorld(context.Background(), worldId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService SearchWorlds", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WorldsAPI.SearchWorlds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService UnpublishWorld", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		httpRes, err := apiClient.WorldsAPI.UnpublishWorld(context.Background(), worldId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorldsAPIService UpdateWorld", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var worldId string

		resp, httpRes, err := apiClient.WorldsAPI.UpdateWorld(context.Background(), worldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
